name: Build & Release Silent Printer

on:
  push:
    tags:
      - 'v*' # only build when a tag like v1.0.0 is pushed
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: node18-win-x64
            ext: exe
          - os: ubuntu-latest
            target: node18-linux-x64
            ext: tar.gz
          - os: ubuntu-latest
            target: node18-linux-arm64
            ext: tar.gz
          - os: macos-latest
            target: node18-macos-x64
            ext: tar.gz
          - os: macos-latest
            target: node18-macos-arm64
            ext: tar.gz

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build with pkg
        run: pkg . --targets ${{ matrix.target }} --output dist/silent-printer-${{ matrix.target }}

      - name: Compress (Linux/Mac)
        if: matrix.ext == 'tar.gz'
        run: tar -czvf dist/silent-printer-${{ matrix.target }}.tar.gz -C dist silent-printer-${{ matrix.target }}

      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: silent-printer-${{ matrix.target }}
          path: |
            dist/*.exe
            dist/*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
