name: Build Silent Printer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: node18-win-x64
            ext: exe
          - os: ubuntu-latest
            target: node18-linux-x64
            ext: tar.gz
          - os: ubuntu-latest
            target: node18-linux-arm64
            ext: tar.gz
          - os: macos-latest
            target: node18-macos-x64
            ext: tar.gz
          - os: macos-latest
            target: node18-macos-arm64
            ext: tar.gz

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build with pkg
        run: pkg . --targets ${{ matrix.target }} --output dist/silent-printer-${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: silent-printer-${{ matrix.target }}
          path: dist/
